### ISSUE TITLE
We don't have a institution agnostic logo

### ISSUE THREAD

**Issue by DannyBrown-xx** [csblogs/csblogs#1]
The current  logo has a big 'H' in it, which stands for Hull.

Seen as we have dropped hull from the name of the system it would be nice to create an entirely new logo which is more generalised.

**Comment by robcrocombe** [comment]
Here is a logo based on what @DannyBrown and I have been discussing. Made in SVG format so it can be scaled/coloured properly. 
![csblogs concept1](https://cloud.githubusercontent.com/assets/4536038/6329707/bdcd4352-bb6a-11e4-9518-237b3e3fce4a.png)

**Comment by Lewis-T** [comment]
Its very similar to the computerphile youtube channel logo https://www.youtube.com/user/Computerphile (At the end of every video the / is added).

maybe use curly braces or some kind of regex notation instead?

**Comment by DannyBrown-xx** [comment]
Logo is as above for now.
