### ISSUE TITLE
create db and design tables

### ISSUE THREAD

**Issue by Godley** [csblogs/csblogs#15]
need to create the database and design tables needed. At minimum, there should probably be something like:
- members
  - id
  - name
  - approved
- privileges  
  - member id
  - level
- feeds
  - member id
  - RSS URL

**Comment by Godley** [comment]
WRONG REPO

**Comment by DannyBrown-xx** [comment]
I envisage the following information being available (though this is of course up for discussion)

_Blogger_
First name, Last Name
City, Country
Feed URI
Website URI
Github Name
Twitter Handle
CV Uri
Array of Organisations[("University of Hull", OrganisationType.University), ("University of York", OrganisationType.University), ("Microsoft Student Partners", OrganisationType.StudentGroup)]
ApprovalStatus (basically users can sign themselves up, so only those with ApprovalStatus true should appear on the blog roll)

**Comment by DannyBrown-xx** [comment]
Oh and a profile picture uri. Possibly gravatar, possibly hosted by us? Oh and Date of Birth for obvious reasons

**Comment by Godley** [comment]
maybe both, though on the gravatar front I would say include an email, as this means they don't have to go hunting for their gravatar uri, we can just import it automatically - then provide the option to replace it with their own upload. This would also serve as their username for the site.

**Comment by apringle** [comment]
I like both lists, I think we should separate what's minimal (i.e name,email,org,blog,approved) and what's nice to have and put the nice to haves in their own tasks.

**Comment by apringle** [comment]
+1 for Gravatar it's nice and easy, just a matter of hashing an email

**Comment by Godley** [comment]
if the rss aggregator also stores posts to a db, that table will need designing as well but that's probably just the same as any other CMS. I don't really know what the reasoning for storing posts was @DannyBrown ?
