### ISSUE TITLE
Cannot now have a 'local copy' of csblogs just by running $node server

### ISSUE THREAD

**Issue by DannyBrown-xx** [csblogs/csblogs#18]
Can someone implement a 'one command' run which sets you up a local mongoldb with the correct tables so you can still have a sandboxed non-live version of the site for debugging etc?

**Comment by emashliles** [comment]
So I just encounterd this issue when I followed the readme. 

I'm not sure what you mean by a 'one command' run - so a few questions

Would this be a bash script or a js script?
Are you planning on tying this to azure?

Looks good so far though :D

**Comment by DannyBrown-xx** [comment]
Hi Emma,

By one command run I just mean that a new dev shouldn't have to be typing out line after line of commands to get a dev environment ready. So either a bash, js or even make file etc would do as long as it was invoked by one command with as few daunting parameters as possible.

As far as azure goes, the webapp is completely platform agnostic except for one line which grabs the monodb connection string from a secure config file on azure (so we don't have usernames and passwords in public github repos). I intend to steer it towards being as platform agnostic as possible!

Sent from my Windows Phone

**Comment by apringle** [comment]
Mongo doesn't require any fixed schema to get started, this can be defined and changed from the application alone. We could use a docker container extending from https://registry.hub.docker.com/_/mongo/ which would allow us to start and stop an isolated local mongo instance with a Dockerfile (config) from our repo.

I'm happy to set this up, devs would just need to have docker installed and it's a couple of simple commands (or short script) to get mongo.

**Comment by DannyBrown-xx** [comment]
@apringle Will docker make the steps I've outlined in README.md easier? Especially of interest, will it reduce changes in commands to be run between different operating systems?

Also, does the developer still have to download mongodb separately to using docker? That seems to be the biggest hurdle for a potential contributor so far?

Seems like it would be pretty simply to make a setup.js which calls brew\apt-get install mongodb etc but this still wouldn't help windows users. (Who, I think will be our biggest contributors based on us attracting Hull devs and market share in general...)

**Comment by emashliles** [comment]
I was having a little look to see if there was an easier way to get the stack setup on windows (it works a dream on linux FYI) 

I would argue that if this project is primarily for students/beginners then the experience of installing mongo is a valuable one especially if they go into developing with Windows. Perhaps a small section in the documentation with well written, excplicit instructions could help and remove some barriers. It would be an unrealistic expereince to have something Windows work so quickly IMO.

**Comment by apringle** [comment]
Docker would be great for setting up a Mongo instance on linux easily, however it may not be as simple as just setting up Mongo on it's own when on other platforms.

I think we should go with the approach @emashliles suggests.

**Comment by DannyBrown-xx** [comment]
I think for the moment the instructions at docs.csblogs.com are enough. 

They're proven to work on each of the 3 major platforms and even though we cant get things up and running with one command a new developer shouldn't feel overwhelmed (3 contributors now have independently set up their dev envs based on the instructions)
