### ISSUE TITLE
database backend

### ISSUE THREAD

**Issue by Godley** [csblogs/csblogs#2]
- what database are we using?
- does it have to be in node.js or can it just provide an API link and use another language
- it needs doing in general

**Comment by DannyBrown-xx** [comment]
One of the things we need to consider when developing csblogs is the availability of documentation. With something as crucial as the database it is vital that the language/runtime (node.js) and the hosting solution (Microsoft Azure) both blend with it well.

Azure has a lot of documentation about using the MongoDB "NoSQL" database. I think we should look into using that, if for only that reason alone. 

Here is one such article: http://azure.microsoft.com/en-gb/documentation/articles/store-mongolab-web-sites-nodejs-store-data-mongodb/

**Comment by DannyBrown-xx** [comment]
After much research we've decided we're using MongoDB with the Mongoose ORM
