### ISSUE TITLE
members list page

### ISSUE THREAD

**Issue by Godley** [csblogs/csblogs#4]
linked to DB, but probs need to do a members list which just pulls links to people's websites directly and lets people visit them

**Comment by DannyBrown-xx** [comment]
I think its also important that we develop the correct kind of admin system so people can update the information we have about them. We don't want to end up in a position where we have out of date information, or information someone is no longer comfortable with being available online for whatever reason.

**Comment by Godley** [comment]
yeah, and there needs to be some kind of join/register section involved so that instead of people emailing to get an account, they can pre-add their info and then an admin just has to press "approve". I'll make another milestone.

**Comment by DannyBrown-xx** [comment]
It needs styling but /bloggers does what is described here.
